import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ChevronLeftIcon, ChevronRightIcon, Cog6ToothIcon, EyeIcon, HomeIcon, TvIcon, XMarkIcon, CheckCircleIcon } from '@heroicons/react/24/outline';
import { Tooltip } from '@components/ui/Tooltip/Tooltip';

type Status = 'operating' | 'stopped' | 'idle';
type Theme = 'light' | 'dark';
type ViewMode = 'shift-wise' | 'hourly';
interface CardData { id:string; machine:string; status:Status; product?:string; produced?:number; target?:number; availability?:number; performance?:number; quality?:number; oee?:number; downSince?:string; downReason?:string; lastUpdate:string; }

const cards: CardData[] = [
 {id:'1',machine:'HT-34-FERO-200',status:'operating',product:'Sfg Amore Papilon Cabinet J...',produced:0,target:2273,availability:73.39,performance:0,quality:100,oee:0,lastUpdate:'about 1 hour ago'},
 {id:'2',machine:'HT-35-HXH-260',status:'operating',product:'Crystal Spoon - NA',produced:70961,target:103680,availability:96.47,performance:73.10,quality:97.37,oee:68.66,lastUpdate:'about 1 hour ago'},
 {id:'3',machine:'HT-27-HT-270',status:'stopped',product:'',produced:0,target:0,oee:0,downSince:'1 day',downReason:'No reason',lastUpdate:'40 minutes ago'},
 {id:'4',machine:'HT-28-HT-270',status:'stopped',product:'15ML MEASURING CUP - NA',produced:104248,target:69120,oee:153.70,downSince:'51 minutes',downReason:'-',lastUpdate:'3 minutes ago'},
 {id:'5',machine:'HT-37-HXH-260',status:'operating',product:'SFG-Papillon 55gm container cap - Nite Blue',produced:7189,target:7252,availability:0,performance:0,quality:0,oee:0,lastUpdate:'6 minutes ago'},
 {id:'6',machine:'HT-38-HXH-260',status:'stopped',product:'Sfg Twister Medium Container - Trans',produced:1594,target:21,oee:55.40,downSince:'43 minutes',downReason:'-',lastUpdate:'6 minutes ago'},
 {id:'7',machine:'HT-39-HXH-260',status:'operating',product:'SFG - Papilon IBM 100gm Cap - NA',produced:31097,target:47127,availability:95.55,performance:71.49,quality:100,oee:68.31,lastUpdate:'about 1 hour ago'},
 {id:'8',machine:'HT-48A-IBM-110',status:'idle',lastUpdate:'6 minutes ago'},
 {id:'9',machine:'HT-49A-IBM-110',status:'idle',lastUpdate:'6 minutes ago'},
 {id:'10',machine:'HT-50A-IBM-110',status:'idle',lastUpdate:'6 minutes ago'},
 {id:'11',machine:'HT-51A-IBM-110',status:'idle',lastUpdate:'6 minutes ago'},
 {id:'12',machine:'LI-40-HT-600',status:'stopped',product:'SFG - CHILDREN TABLE - Blue',produced:121,target:3,oee:52.39,downSince:'5 minutes',downReason:'No reason',lastUpdate:'8 minutes ago'},
 {id:'13',machine:'LI-41-HXM-630',status:'operating',product:'SFG - 200ltr Drum Cover - NA',produced:869,target:6,availability:91.86,performance:108.61,quality:97.09,oee:96.87,lastUpdate:'14 minutes ago'},
 {id:'14',machine:'MI-04-FU-110',status:'operating',product:'SFG - Lemon Squeezer - NA',produced:1920,target:2400,availability:69.26,performance:121.20,quality:98.16,oee:82.40,lastUpdate:'about 1 hour ago'},
 {id:'15',machine:'MI-05-HT-120',status:'operating',product:'Dinner Plate - NA',produced:2839,target:4320,availability:88.90,performance:76.54,quality:99.59,oee:67.77,lastUpdate:'about 1 hour ago'},
 {id:'16',machine:'MI-06-HT-120',status:'operating',product:'Sfg Amore Papilon Cabinet Junior - Knob - NA',produced:5039,target:12342,availability:58.01,performance:74.81,quality:99.25,oee:43.07,lastUpdate:'about 1 hour ago'},
 {id:'17',machine:'MI-07-HT-120',status:'operating',product:'SFG - Diamond Mug - NA',produced:1607,target:2880,availability:62.24,performance:94.13,quality:98.10,oee:57.47,lastUpdate:'about 1 hour ago'},
 {id:'18',machine:'MI-08-FU-150',status:'operating',product:'SFG - Lemon Squeezer Container - Trans',produced:1956,target:2400,availability:85.11,performance:99.26,quality:99.56,oee:84.11,lastUpdate:'44 minutes ago'},
 {id:'19',machine:'MI-09-FU-150',status:'operating',product:'SFG - 40gm/20cc Container Cap - NA',produced:44528,target:65207,availability:90.13,performance:78.40,quality:100,oee:70.66,lastUpdate:'44 minutes ago'},
 {id:'20',machine:'MI-10-HT-160',status:'operating',product:'Sfg Twister Medium Cover - NA',produced:4561,target:7200,availability:76.53,performance:64.91,quality:100,oee:49.67,lastUpdate:'44 minutes ago'},
 {id:'21',machine:'MI-11-HT-160',status:'stopped',product:'Beer Mug - NA',produced:773,target:1728,oee:42.87,downSince:'52 minutes',downReason:'-',lastUpdate:'5 minutes ago'},
 {id:'22',machine:'MI-12-HT-160',status:'operating',product:'SFG - Crystal/Deep Bucket 2ltr Body - NA',produced:369,target:21,availability:0,performance:0,quality:0,oee:0,lastUpdate:'8 minutes ago'},
];

function Ring({value, light=false }: {value:number; light?:boolean}) { const pct=Math.max(0,Math.min(100,value)); const r=43,c=2*Math.PI*r; return <div className="relative w-[92px] h-[92px] shrink-0"><svg className="w-full h-full -rotate-90"><circle cx="46" cy="46" r={r} fill="none" stroke={light?'rgba(255,255,255,.22)':'rgba(255,255,255,.18)'} strokeWidth="8"/><circle cx="46" cy="46" r={r} fill="none" stroke={light?'#FFE7D9':'#DFFBEA'} strokeWidth="8" strokeDasharray={`${c*pct/100} ${c}`} strokeLinecap="round"/></svg><div className="absolute inset-0 flex items-center justify-center text-[16px] font-normal">{value.toFixed(2)}%</div></div> }
function Tool({label,children,onClick}:{label:string;children:React.ReactNode;onClick?:()=>void}) {return <Tooltip content={label}><button onClick={onClick} aria-label={label} className="h-9 px-3 rounded-[4px] border border-[#3048A8] text-[#3048A8] bg-white hover:bg-[#EEF2FF] flex items-center gap-2 text-[11px]">{children}</button></Tooltip>}
function MachineCard({card}:{card:CardData}) { const stopped=card.status==='stopped', idle=card.status==='idle'; const bg=stopped?'#C9002B':idle?'#355365':'#00851B'; const progress=card.target?Math.min(100,(card.produced||0)/card.target*100):0; return <article className="rounded-[5px] p-3 sm:p-4 text-white min-h-[176px] shadow-[0_1px_2px_rgba(0,0,0,.15)]" style={{background:bg}}>
  <div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="text-[18px] sm:text-[20px] leading-tight font-medium truncate">{card.machine}</div>{idle?<div className="text-[20px] sm:text-[22px] mt-3 leading-tight">No plan<br/>available</div>:stopped?<><div className="text-[11px] mt-3 opacity-95">Down since</div><div className="text-[20px] sm:text-[23px] leading-tight">{card.downSince}</div><div className="text-[11px] mt-2 opacity-95">Down reason</div><div className="text-[15px] sm:text-[16px]">{card.downReason}</div></>:<><div className="text-[13px] mt-2 truncate">{card.product}</div><div className="flex items-baseline justify-end gap-1 mt-2"><span className="text-[21px] sm:text-[24px]">{card.produced}</span><span className="text-[12px]">/{card.target}</span></div><div className="h-[2px] bg-white/35 mt-1"><div className="h-full bg-white/80" style={{width:`${progress}%`}}/></div><div className="grid grid-cols-2 gap-x-4 gap-y-1 mt-2 text-[11px]"><div><span>Availability</span><strong className="block text-[16px]">{card.availability?.toFixed(2)}%</strong></div><div><span>Performance</span><strong className="block text-[16px]">{card.performance?.toFixed(2)}%</strong></div><div><span>Quality</span><strong className="block text-[16px]">{card.quality?.toFixed(2)}%</strong></div></div></>}</div>{(stopped||idle||card.oee!==undefined)&&<Ring value={card.oee||0}/>}</div>
  <div className="flex items-center gap-1.5 mt-3 text-[10px] opacity-90"><CheckCircleIcon className="w-4 h-4"/>Last update {card.lastUpdate}</div>
 </article> }

function Configure({open,onClose,theme,setTheme,view,setView,filters,setFilters}:{open:boolean;onClose:()=>void;theme:Theme;setTheme:(x:Theme)=>void;view:ViewMode;setView:(x:ViewMode)=>void;filters:string[];setFilters:(x:string[])=>void}) { if(!open)return null; const toggle=(x:string)=>setFilters(filters.includes(x)?filters.filter(f=>f!==x):[...filters,x]); return <aside className="fixed right-0 top-0 bottom-0 z-50 w-[320px] max-w-[92vw] bg-white dark:bg-[#111827] shadow-2xl border-l border-[#D8DDE6] overflow-y-auto"><div className="sticky top-0 flex items-center justify-between p-4 bg-white dark:bg-[#111827] border-b border-[#D8DDE6]"><h2 className="text-[17px]">Configure</h2><Tooltip content="Close configuration"><button onClick={onClose}><XMarkIcon className="w-5 h-5"/></button></Tooltip></div><div className="p-4 space-y-5 text-[12px] text-[#475569]">
  <section><div className="uppercase text-[10px] mb-2">Theme</div><div className="space-y-2"><label className="flex gap-2 items-center"><input type="radio" checked={theme==='light'} onChange={()=>setTheme('light')}/> Light</label><label className="flex gap-2 items-center"><input type="radio" checked={theme==='dark'} onChange={()=>setTheme('dark')}/> Dark</label></div></section>
  <section><div className="uppercase text-[10px] mb-2">View</div><div className="space-y-2"><label className="flex gap-2 items-center"><input type="radio" checked={view==='shift-wise'} onChange={()=>setView('shift-wise')}/> Shift-wise</label><label className="flex gap-2 items-center"><input type="radio" checked={view==='hourly'} onChange={()=>setView('hourly')}/> Hourly</label></div></section>
  {['Availability','Performance','Quality','OEE'].map(x=><section key={x}><div className="uppercase text-[10px] mb-2">{x}</div><div className="flex gap-2"><select className="h-8 border-b border-[#CBD5E1] bg-transparent outline-none"><option>&gt;=</option><option>&lt;=</option></select><input className="h-8 w-full border-b border-[#CBD5E1] outline-none" defaultValue="0"/></div></section>)}
  <section><div className="uppercase text-[10px] mb-2">Status</div><div className="flex flex-wrap gap-2">{['Operating','Stopped','Idle'].map(x=><button key={x} onClick={()=>toggle(x.toLowerCase())} className={`px-3 py-1.5 rounded-full border ${filters.includes(x.toLowerCase())?'bg-[#E2F8E8] border-[#16A34A] text-[#15803D]':'border-[#CBD5E1]'}`}>{x}</button>)}</div></section>
 </div></aside> }

export default function LiveShopfloor(){
 const navigate=useNavigate(); const [theme,setTheme]=useState<Theme>('light'); const [view,setView]=useState<ViewMode>('shift-wise'); const [config,setConfig]=useState(false); const [page,setPage]=useState(0); const [preview,setPreview]=useState(false); const [filters,setFilters]=useState<string[]>(['operating','stopped','idle']); const [tv,setTv]=useState(false);
 const pageSize=6; const filtered=useMemo(()=>cards.filter(c=>filters.includes(c.status)),[filters]); const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)); const visible=filtered.slice(page*pageSize,page*pageSize+pageSize); useEffect(()=>{if(page>=pageCount)setPage(0)},[page,pageCount]);
 const counts={total:49,operating:31,stopped:12,idle:6};
 const rootClass=theme==='dark'?'bg-[#111] text-white':'bg-white text-[#1F2937]';
 if(preview||tv) return <div className={`${rootClass} min-h-screen p-3 sm:p-4`}><div className="flex justify-end mb-2"><Tool label="Exit preview" onClick={()=>{setPreview(false);setTv(false)}}><XMarkIcon className="w-4 h-4"/>Exit</Tool></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{visible.map(c=><MachineCard key={c.id} card={c}/>)}</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4">{[[counts.total,'Machines','bg-[#1F1F1F]'],[counts.operating,'Operating','bg-[#00851B]'],[counts.stopped,'Stopped','bg-[#C9002B]'],[counts.idle,'Idle','bg-[#355365]']].map(([n,l,b]:any)=><div className={`${b} rounded-[5px] text-white text-center py-3`} key={l}><div className="text-[28px]">{n}</div><div>{l}</div></div>)}</div></div>;
 return <div className={`${rootClass} min-h-screen transition-colors`}>
   <header className="h-[72px] px-4 sm:px-5 flex items-center justify-between border-b border-[#D8DDE6] bg-white dark:bg-[#111827]"><div className="flex items-center gap-4"><div className="text-[14px] font-medium flex items-center gap-2"><span className="font-bold text-[#3B82C4]">Shop</span><span className="text-[#1EAA6D]">Worx</span></div><h1 className="text-[20px] sm:text-[24px] font-normal">Shift-wise shopfloor dashboard</h1></div><div className="flex items-center gap-2"><Tool label="Send dashboard to TV" onClick={()=>setTv(true)}><TvIcon className="w-4 h-4"/> <span className="hidden sm:inline">Send to TV</span></Tool><Tool label="Preview dashboard" onClick={()=>setPreview(true)}><EyeIcon className="w-4 h-4"/><span className="hidden sm:inline">Preview</span></Tool><Tool label="Configure dashboard" onClick={()=>setConfig(true)}><Cog6ToothIcon className="w-4 h-4"/><span className="hidden sm:inline">Configure</span></Tool><Tool label="Return to Home" onClick={()=>navigate('/')}><HomeIcon className="w-4 h-4"/><span className="hidden sm:inline">Home</span></Tool></div></header>
   <main className="p-3 sm:p-4 lg:p-5 max-w-[1500px] mx-auto"><div className="grid grid-cols-2 xl:grid-cols-4 gap-3 mb-3">{[[counts.total,'Machines','bg-[#1F1F1F]'],[counts.operating,'Operating','bg-[#00851B]'],[counts.stopped,'Stopped','bg-[#C9002B]'],[counts.idle,'Idle','bg-[#355365]']].map(([n,l,b]:any)=><div key={l} className={`${b} rounded-[5px] text-white text-center py-3 sm:py-4`}><div className="text-[28px] sm:text-[34px] leading-none">{n}</div><div className="text-[16px] sm:text-[18px] mt-1">{l}</div></div>)}</div>
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{visible.map(c=><MachineCard key={c.id} card={c}/>)}</div>
    <div className="flex items-center justify-center gap-2 mt-4"><Tooltip content="Previous machines"><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))} className="p-2 disabled:opacity-30"><ChevronLeftIcon className="w-5 h-5"/></button></Tooltip>{Array.from({length:Math.min(pageCount,18)},(_,i)=><button key={i} onClick={()=>setPage(i)} aria-label={`Page ${i+1}`} className={`w-2.5 h-2.5 rounded-full ${page===i?'bg-[#6B7280] scale-125':'bg-[#9CA3AF]'}`}/>) }<Tooltip content="Next machines"><button disabled={page===pageCount-1} onClick={()=>setPage(p=>Math.min(pageCount-1,p+1))} className="p-2 disabled:opacity-30"><ChevronRightIcon className="w-5 h-5"/></button></Tooltip></div>
    <footer className="mt-5 flex flex-wrap items-center justify-between gap-3 text-[13px] text-[#475569]"><span>ShopWorx • Shift-wise shopfloor dashboard</span><span>{new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} | Shift2</span></footer>
   </main><Configure open={config} onClose={()=>setConfig(false)} theme={theme} setTheme={setTheme} view={view} setView={setView} filters={filters} setFilters={setFilters}/>
 </div>
}
